### ISSUE TITLE
Missing nuget config

### ISSUE THREAD

**Issue by trbngr** [brockallen/BrockAllen.IdentityReboot#1]
To make it easy for people to use the samples, you should include a NuGet.config file at the root of the solution.

https://gist.github.com/trbngr/9013961

**Comment by brockallen** [comment]
Ah, not a bad idea. I didn't know about this feature. Thx.

**Comment by brockallen** [comment]
Actually, I think i'll switch to the official beta... still, thanks :)

**Comment by trbngr** [comment]
Even better! ;)

**Comment by brockallen** [comment]
Just pushed these updates now.
