### ISSUE TITLE
Iteration count being set via timestamp rather than year

### ISSUE THREAD

**Issue by falconmick** [brockallen/BrockAllen.IdentityReboot#10]
Forgive me if this is achievable already, still learning your system.

But Currently it looks as if you can configure the Iteration count to be used either through manually providing the Iteration count OR through use of a value stored for each year. Wouldn't a system which allows the user to to specify a timestamp as the identifier for the number of iterations required?

Just following the mentality of making your password hashing process to take roughly 1 second, would be helpful if in February I decided to stick 8 high end server CPU's into a box rather than a Pentium 3 that I could specify the new value for people to use after the date in which I upgraded.

Once again, sorry if it is already possible, I'm still learning.

**Comment by brockallen** [comment]
I agree that's an interesting approach and in fact I prototyped it and added it as a feature, but I found it somewhat unreliable. The results can vary based upon machine load and I found it very difficult to make it work well. So I ended up removing it.

**Comment by falconmick** [comment]
Please skip to "I am sorry if this is hard to read. In summary:" if you get lost in my poor writing skills or just want it simple.

I think I understand better your choice now.

I raise a simple point here: you'r basing your default hash iterations via a generic equation of computer power doubles each year so I should double my iterations each year. Wouldn't a much more sustainable idea be to based it off of your available power and not a generic function?

I keep re-writing my response and disliking my post, so I'll keep it simple:
Why not replace the automatic increase hash count system with one which is based via another table in your db which contains a unique ID referring to  an iteration count, you then save the id in the user's account rather than iteration count. The benefit of this is, if you were to get a brand new server, you could immediately improve the security of your system and choose a iteration right for you! 

If users still wanted an automatically increasing iteration, they could set a configuration setting and then when the server goes to choose how many iterations to use, it will compair the current iteration count (via the new table) and if the auto value is greater, add a new value to the table of the auto generated value of the bigger new year value, this way users could manually up the value when ever they want but still have the magic of automatic security improvements.

I am sorry if this is hard to read. In summary:
Change auto iteration system to have a table of iteration counts, users manually select the right iteration count for their servers power and then update it when ever needed. Also give the users the ability to choose to fallback to the automatic value IF the current iteration value is < the automatically generated one (via year and iteration doubling)

**Comment by brockallen** [comment]
I think these are all interesting suggestions. Feel free to implement them and if they look good, I'd be willing to consider adding them.

**Comment by brockallen** [comment]
Any progress?
