### ISSUE TITLE
Many compile errors after update Microsoft.AspNet.Identity to 2.1

### ISSUE THREAD

**Issue by mikeandersun** [brockallen/BrockAllen.IdentityReboot#11]
I Used IdentityReboot with Microsoft.AspNet.Identity 2 and worked fine. After update Microsoft.AspNet.Identity to 2.1 all thing crashed with many compile errors.
Id it a plan to support Microsoft.AspNet.Identity  2.1?
Best,

**Comment by brockallen** [comment]
I can look into it. thx for reporting.

**Comment by brockallen** [comment]
I didn't see any errors or problems when updating to v2.1. I updated the master branch for AspNetId v2.1 and I added the MVC sample app with the necessary changes to incorporate IdentityReboot.
