### ISSUE TITLE
[Question] AdaptivePasswordHasher as a separate NuGet package?

### ISSUE THREAD

**Issue by loctanvo** [brockallen/BrockAllen.IdentityReboot#12]
Hi,

First of all, thank you for providing IdentityReboot. I'm wondering if you are planning on separating AdaptivePasswordHasher and Crypto as a separate NuGet package? Right now, we don't need the whole AspNet.Identity-package, and it'd be nice to avoid a dependency on that package. However, I like your implementation of AdaptivePasswordHasher and would need to implement something similar. A small NuGet package would be very suitable for us.

In advance, thanks for your answer.

Loc

**Comment by brockallen** [comment]
There's not much to the code -- feel free to copy it.

**Comment by loctanvo** [comment]
Thanks for the answer. Will consider doing that until we have the need for IdentityReboot.
