### ISSUE TITLE
[Question] How to apply "system-wide" key/salt

### ISSUE THREAD

**Issue by loctanvo** [brockallen/BrockAllen.IdentityReboot#13]
Hi, 

Given that we use IdentityReboot, how would you apply a "system-wide" key to the HMAC function? I'm thinking about [this part of OWASP's cheat sheet](https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet#Leverage_Keyed_functions). I would like to hash the password with one salt per user, and in addition use another application key stored somewhere outside the user DB.

Just hope you could share some opinions on that. Thanks in advance.

Loc

**Comment by brockallen** [comment]
You could use the decorator pattern and have your implementation append the app-wide salt to the incoming values.

**Comment by loctanvo** [comment]
That's similar to what I was thinking off. Thanks for the answer.
