### ISSUE TITLE
Package no longer functions under MVC 5/EF 6

### ISSUE THREAD

**Issue by Eclipse-Computing** [brockallen/BrockAllen.IdentityReboot#14]
This issue has been tested with a raw ASP.NET MVC 5 project as well as a hybrid MVC/API project. In both cases, adding all the required items ended up with `ITwoFactorCode` in `IdentityModels.cs` being painted:

`public class ApplicationUser : IdentityUser, ITwoFactorCode {`

And with the error messages:

```
'ApplicationUser' does not implement interface member 'ITwoFactorCode<string>.HashedTwoFactorAuthCode'
'ApplicationUser' does not implement interface member 'ITwoFactorCode<string>.DateTwoFactorAuthCodeIssued'
```

As a test I was very, very careful to open up a new project with nothing extra added, and then install and configure IdentityReboot.

As a note: I have also de-pluralized and renamed the base tables:

```
    protected override void OnModelCreating(DbModelBuilder modelBuilder) {
      base.OnModelCreating(modelBuilder);
      modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
      modelBuilder.Entity<IdentityUser>().ToTable("Users");
      modelBuilder.Entity<ApplicationUser>().ToTable("Users").Property(p => p.Id).HasColumnName("Id");
      modelBuilder.Entity<IdentityRole>().ToTable("Roles");
      modelBuilder.Entity<IdentityUserRole>().ToTable("UserRoles");
      modelBuilder.Entity<IdentityUserLogin>().ToTable("UserLogins");
      modelBuilder.Entity<IdentityUserClaim>().ToTable("UserClaims");
```

…but this was also done for prior projects as well.

As a second note: I am using the latest Visual Studio 2015 v14.0.25422.01 Update 3.

I also need to know if IdentityReboot is something I can add to a project after launch, or if it is needed from the beginning to properly configure user accounts. The existence of per-account adaptive hashing suggests the latter, but I would like confirmation.

**Comment by brockallen** [comment]
Perhaps there was a breaking change in ASP.NET Identity? If you find what API changed, then let me know and/or submit a PR, please.

**Comment by Eclipse-Computing** [comment]
Will do, however I am a “junior” programmer at best, and I would be pressed to know where to start looking in the first place.

One of my more pressing questions, though, involves past projects: If I have a project that employs this package, and I update the project itself, will I be able to remove this package and still have the entire Identity system continue to function with prior-created accounts? Or will removal of this package break all accounts previously created? The per-account adaptive hashing is what is worrying me.

**Comment by Eclipse-Computing** [comment]
Hmmm… Microsoft.AspNet.Identity.Core is still at 2.2.1, which hasn't changed since early 2015. EntityFramework 2.2.1 came out about the same time. So I would have to say, no -- there was no breaking change.

Going to try again with a test project, to really confirm if something has broken.

**Comment by brockallen** [comment]
Ok, keep me posted. Thanks.
