### ISSUE TITLE
RTM version of ASP.Net Identity 2.0 has some breaking changes

### ISSUE THREAD

**Issue by mtimms** [brockallen/BrockAllen.IdentityReboot#3]
ASP.NET Identity Core Version: 2.0.0-rtm-140307 from the nightly builds has a couple of breaking changes that affect IdentityReboot. 

**NotifyAsync** function added to interface IUserTokenProvider.   Affects IdentityReboot StoredTwoFactorProvider. Workaround was to add the same code that was in the DataProtectorTokenProvider.  Namely:

```
        public Task NotifyAsync(string token, UserManager<TUser, TKey> manager, TUser user)
        {
            return Task.FromResult<int>(0);
        }

```

UserManager function **VerifyPassword** renamed to **VerifyPasswordAsync**.   Affects override in IdentityRebootUserManger.

**Comment by brockallen** [comment]
Yea, I expected there would be -- mainly because all the things I pointed out that were possible flaws they've started to fix.

I'll look into the changes next week.

**Comment by brockallen** [comment]
Ok, updated to RTM. Given the addition of the brute force code in their library, I removed it from IR. The rest remains. Also, I added some new features to the adaptive password hasher -- it's quite nice :) I need to merge it back into MR now.
