### ISSUE TITLE
Nuget Conflict with 2.0.0-rtm

### ISSUE THREAD

**Issue by codemonkey21** [brockallen/BrockAllen.IdentityReboot#4]
The newest IdentityReboot.Ef has a dependence on <dependency id="BrockAllen.IdentityReboot" version="2.0.0-rtm-140311" />  but that is currently versioned 1.0.0-rtm. 

When I try to update the packages in the package manager, it's throwing a conflict error.

**Comment by brockallen** [comment]
Yea, sorry -- I guess nuget doesn't know about the nightlys. I'll update the nuget, but you'll need to manually load ASP.NET Identity and its EF from the nightly server.

**Comment by brockallen** [comment]
Ok, it seems fixed now, but you'll have to manually get ASP.NET Identity from the nightlys.
