### ISSUE TITLE
AdaptivePasswordHasher never returns PasswordVerificationResult.SuccessRehashNeeded

### ISSUE THREAD

**Issue by WalkerCodeRanger** [brockallen/BrockAllen.IdentityReboot#6]
The AdaptivePasswordHasher should return PasswordVerificationResult.SuccessRehashNeeded when the number of iterations a password is hashed with is below the current IterationCount (including when verifying a legacy password hash whose iterations are assumed to be 1000).  Since the number of iterations estimated when using the targetDuration may fluctuate somewhat perhaps there should be some allowance for lower iterations, say 30%?

I know that the ASP.NET identity library doesn't currently do anything with RehashNeeded, but there is an issue out there for it (https://aspnetidentity.codeplex.com/workitem/1928#).  Also, it appears from the disassembly that it will treat anything that is not failure as success.

**Comment by brockallen** [comment]
Fixed. Thx.
