### ISSUE TITLE
 IdentityRebootUserManager doesn't default to AdaptivePasswordHasher?

### ISSUE THREAD

**Issue by WalkerCodeRanger** [brockallen/BrockAllen.IdentityReboot#7]
In your [Introducing IdentityReboot](http://brockallen.com/2014/02/11/introducing-identityreboot/) post you state "Also, by default, the `IdentityRebootUserManager` automatically configures and uses the `AdaptivePasswordHasher` mentioned above." But when I create an `IdentityRebootUserManager` I have to manually set `PasswordHasher = new AdaptivePasswordHasher()`. Looking at the code I would think this needs added to the `IdentityRebootUserManager` constructor.

**Comment by brockallen** [comment]
Yea, I changed my mind and decided to not register it automatically. You'll have to explicitly set the AdaptivePasswordHasher.

**Comment by WalkerCodeRanger** [comment]
Really?  Isn't it standard to have things secure by default?  I feel like the password hashing is one of the major purposes of your library and you wouldn't want people to accidentally not have it configured. Also, it plays well with existing databases of hashed passwords so it isn't like the dev needs to do something before turning it on.  I've submitted a pull request.  You can see that the changes are pretty simple and straightforward.

Ultimately, it is your project.

**Comment by brockallen** [comment]
Ok, I merged in the PR. Thanks.
